# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jsStudyBlog
email: mansukong@naver.com
description: > # this means to ignore newlines until "baseurl:"
  javascript & front end developer site.
baseurl: "jsStudyBlog" # the subpath of your site, e.g. /blog
lang: "ko"
url: "/" # the base hostname & protocol for your site
twitter_username: 
github_username:  jsStudyGroup
disqus_username: mansukong

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: nested


images: '/assets/images'
